# Generated by Django 5.1.6 on 2025-06-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vege", "0004_receipe_receipe_view_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipe",
            name="receipe_view_count",
            field=models.IntegerField(),
        ),
    ]
