# Generated by Django 5.1.4 on 2025-06-22 06:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vege", "0005_alter_receipe_receipe_view_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="receipe",
            old_name="receipe_view_count",
            new_name="recipe_view_count",
        ),
    ]
