# Generated by Django 5.1.4 on 2025-06-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vege", "0007_department_studentid_alter_receipe_recipe_view_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="student_address",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="student",
            name="student_age",
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name="student",
            name="student_email",
            field=models.EmailField(default="", max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name="student",
            name="student_name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
