# Generated by Django 5.1.4 on 2025-07-19 11:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vege", "0009_subject_subjectmarks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="department",
        ),
        migrations.RemoveField(
            model_name="student",
            name="student_id",
        ),
        migrations.RemoveField(
            model_name="subjectmarks",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="subjectmarks",
            name="student",
        ),
        migrations.DeleteModel(
            name="Subject",
        ),
        migrations.DeleteModel(
            name="Department",
        ),
        migrations.DeleteModel(
            name="StudentID",
        ),
        migrations.DeleteModel(
            name="Student",
        ),
        migrations.DeleteModel(
            name="SubjectMarks",
        ),
    ]
