# Generated by Django 5.1.4 on 2025-10-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vege", "0012_alter_receipe_receipe_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipe",
            name="receipe_image",
            field=models.FileField(upload_to="receipes"),
        ),
    ]
