# Generated by Django 5.1.4 on 2025-10-02 16:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vege", "0013_alter_receipe_receipe_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipe",
            name="receipe_image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="receipes"
            ),
        ),
    ]
